### ISSUE TITLE
run the exe in background

### ISSUE THREAD

**Issue by vicdilou** [davidramiro/fluxee#3]
Hello,
it's possible to run the program in the background?
Thank you.

**Comment by davidramiro** [comment]
Sadly not easily, I have yet to find a way to make the tool run flawlessly in the background.
For now, there is a "dirty" workaround using pythonw and a Batch script (credits to @mkierc):

[batch-background.zip](https://github.com/davidramiro/fluxee/files/2192322/batch-background.zip)
Place those two files into the fluxee folder, use start.bat to run the script and close the cmd window. Use stop.bat when you want to terminate the background process.

Keep in mind that this will not show any errors, if something doesn't work check the stderr.txt that the script creates.

**Comment by davidramiro** [comment]
After a second glance over this issue: running bottle.py, a substancial part of this script, is simply not possible with pythonw. Hence this is not possible, sadly.

See https://github.com/bottlepy/bottle/issues/1104
