### ISSUE TITLE
Corrupted Release

### ISSUE THREAD

**Issue by lepathie** [davidramiro/fluxee#5]
I can't extract the archive of your new release for some reason. Maybe the files got corrupted. Downloaded and tried multiple times.

**Comment by davidramiro** [comment]
I reuploaded it using another compression method, would you be so kind and try again now?

Regards,
David

**Comment by lepathie** [comment]
Works fine now. Thank you.

**Comment by davidramiro** [comment]
Great, thanks for your feedback.
