### ISSUE TITLE
Seems to not work anymore

### ISSUE THREAD

**Issue by ThoWmas31** [davidramiro/fluxee#7]
Hello, since some days the Fluxee app crash when tying to initializing the lamp, i checked the yeelight app and the third control access is still authorized, i updated python and fluxee, i don't know where is the problem

**Comment by davidramiro** [comment]
Hey,

are all lamps on the latest firmware? I just checked myself with four different kinds of lamps, all of them updated to the latest firmware and it works as expected:

![debian_F0FmYEXPRk](https://user-images.githubusercontent.com/30576493/64068377-9bc29900-cc37-11e9-94c1-2da26824b4bf.png)

Which kind of lamp are you having an issue with? The specific model would be very helpful.

**Comment by ThoWmas31** [comment]
yes updated to the last version, and i do a reset of my lamp. Windows update Ok , i'm not able to find where is the problem :-/

**Comment by davidramiro** [comment]
Could you tell me the specific lamp model you are having this issue with?

**Comment by ThoWmas31** [comment]
named in application : Yeelight Color Bulb, also i check my firewall didn't change anything

Crash at this step : https://i.imgur.com/cC3lQZv.jpg

**Comment by davidramiro** [comment]
Another test, with the precompiled .exe as on your setup and with the Yeelight Color Bulb v1 and v2:

![fluxee_CG3sQSKKpA](https://user-images.githubusercontent.com/30576493/64069086-9c146180-cc42-11e9-9a69-d52323f76cc6.png)

So this is exactly like your setup and works fine - if it did work before and stopped working now suddenly, I suppose something on your end went wrong. Maybe try turning the LAN control off and on again.

**Comment by ThoWmas31** [comment]
already reseted twice and lan control off and on again. what is your python version ?

**Comment by davidramiro** [comment]
3.7.4. Shouldn't matter for you, as you are using the precompiled exe, it comes with Python included. You can try installing 3.7.x and running `python fluxee.py` manually, it would definitely output a specific error.

**Comment by ThoWmas31** [comment]
i try to create a .bat files with 
`fluxee.py
pause`

and i got this : https://i.imgur.com/xcGiFjx.jpg

(not sure if it's it could help)

**Comment by davidramiro** [comment]
Weird, 3.4.x and up should come with enum included, at least I thought. Anyways, try running `pip install --upgrade pip enum34` and try again.

**Comment by ThoWmas31** [comment]
i think a found the debug view 

`Welcome to fluxee by davidramiro
Reading config...
Initializing...
Initializing Yeelight at 192.168.1.14
Traceback (most recent call last):
  File "C:\Users\thoma\Desktop\fluxee-master (1)\fluxee-master\yeelight\main.py", line 302, in send_command
    self._socket.send((json.dumps(command) + "\r\n").encode("utf8"))
  File "C:\Users\thoma\Desktop\fluxee-master (1)\fluxee-master\yeelight\main.py", line 169, in _socket
    self.__socket.connect((self._ip, self._port))
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\thoma\Desktop\fluxee-master (1)\fluxee-master\fluxee.py", line 80, in <module>
    main()
  File "C:\Users\thoma\Desktop\fluxee-master (1)\fluxee-master\fluxee.py", line 62, in main
    state = bulb.get_properties(requested_properties=['power'])
  File "C:\Users\thoma\Desktop\fluxee-master (1)\fluxee-master\yeelight\main.py", line 270, in get_properties
    response = self.send_command("get_prop", requested_properties)
  File "C:\Users\thoma\Desktop\fluxee-master (1)\fluxee-master\yeelight\main.py", line 308, in send_command
    raise_from(BulbException("A socket error occurred when sending the command."), ex)
  File "C:\Users\thoma\Desktop\fluxee-master (1)\fluxee-master\future\utils\__init__.py", line 398, in raise_from
    exec(execstr, myglobals, mylocals)
  File "<string>", line 1, in <module>
yeelight.main.BulbException: A socket error occurred when sending the command.
>>> `

**Comment by davidramiro** [comment]
Ah, unfortunately `socket.timeout: timed out` means the lamp is simply not responding. I suggest you post this issue to the [official Yeelight forums](https://forum.yeelight.com/), maybe there is some issue on your current firmware?

**Comment by davidramiro** [comment]
On another thought - maybe the lamp got a new IP from your router? Please check if the IP in the config file matches its current network adress.

**Comment by ThoWmas31** [comment]
I connect to my router and ip adress is the same.

The error could come from a problem with UTF8 ?

**Comment by ThoWmas31** [comment]
Lamp to wifi seems correct , i could change parameter like intensity or color from my phone

**Comment by davidramiro** [comment]
No, since the script is definitely talking to the correct IP address, see `Initializing Yeelight at 192.168.1.14` . Probably an issue with the LAN control. Unfortunately nothing I can do about it right now. As I showed you, the script is still working and you were the only one with this kind of issue so far 🙁 I'd really try opening a thread on the Yeelight forums, their staff is very helpful. Just tell them your lamp cannot communicate via the network API.

**Comment by ThoWmas31** [comment]
YOu have already done a amazing works thx for all :)
