### ISSUE TITLE
Fluxee not working after changing config

### ISSUE THREAD

**Issue by rafaeldatarock** [davidramiro/fluxee#8]
Hi David,

I changed the config file while Fluxee was running (Set StaticBrightness from False to True).
Fluxee gave some errors, I didn't capture a screenshot of them unfortunately, but seems logical 'cause of the sudden change in config.
I restarted fluxee.exe but now it hangs at Initializing (see screenshot) and just terminates after about 4 seconds.

I'm on Windows 10. Fluxee has always worked before, even when changing the config file. (I believe I even changed the config file while fluxee was running once before, which didn't cause any problems then.)

I know it's not a lot of information to go by, so please let me know if you need to know more. Hopefully I can provide.

![fluxee screenshot](https://user-images.githubusercontent.com/43268243/66769747-2abd0500-eeb6-11e9-9027-daaa88bb57e4.png)

**Comment by rafaeldatarock** [comment]
Wow, so sorry.
Turns out my lamp was just disconnected from my network, even though it was turned on like normal.
Turned it off and on again, now it's working perfectly fine.

**Comment by davidramiro** [comment]
No worries, glad it's working again.
