### ISSUE TITLE
Bulb closed the connection

### ISSUE THREAD

**Issue by norbiq** [davidramiro/fluxee#9]
Hi David,

I have just found out about Fluxee and got real excited. I downloaded the package and followed the config guidelines. After setting up everything I ran fluxee.exe and I got this message:

```
Welcome to fluxee by davidramiro
Reading config...
Initializing...
Initializing Yeelight at 192.168.73.112
Traceback (most recent call last):
  File "fluxee.py", line 83, in <module>
  File "fluxee.py", line 65, in main
  File "yeelight\main.py", line 313, in get_properties
  File "yeelight\main.py", line 377, in send_command
yeelight.main.BulbException: Bulb closed the connection.
[15112] Failed to execute script fluxee
```

I have the Smart LED bulb 1S (model: YLDP13YL). I tried disabling checking the bulb state in the config.ini but it did not change anything. What do you think could cause this problem?

Thanks.

**Comment by norbiq** [comment]
Nevermind.

**Comment by cjmanca** [comment]
I'm having this same issue. How did you fix it?

**Comment by StanislavMayorov** [comment]
I have the same bug time to time. I run it on 2 windows pc each is connected to its own device. Devices are yeelight Arwen Ceiling Light 550C YLXD013-C and Yeelight LED Ceiling Light 480.
